# fly.toml app configuration file generated for late-wind-4739 on 2023-08-08T15:03:38-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "late-wind-4739"
primary_region = "phx"
kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/usr/share/nginx/html/"
  url_prefix = "/"
